services:
  redo:
    build: .
    container_name: redo
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - /mnt/datos/redo:/app/data
    environment:
      - TZ=Europe/Madrid
      - REDO_DB_PATH=/app/data/redo.db
      - REDO_NETWORK=${REDO_NETWORK}
      - REDO_SCAN_INTERVAL=300
      - NTFY_TOPIC=${NTFY_TOPIC}
    restart: always
